config/routes.rb
Rails.application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :contacts
  resources :pages, :path => '/'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :slide
  has_attached_file :picture,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
	  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	  # add a delete_<asset_name> method: 
	  attr_accessor :delete_picture
	  before_validation { self.picture.clear if self.delete_picture == '1' }

  scope :show, -> { where(show: true).order('position ASC') }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :slide
end

app/models/page.rb
class Page < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: :slugged
  	has_many :slides, -> { order 'position asc' }
  	has_attached_file :icon,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
	  validates_attachment_content_type :icon, :content_type => /\Aimage\/.*\Z/
	  # add a delete_<asset_name> method: 
	  attr_accessor :delete_icon
	  before_validation { self.icon.clear if self.delete_icon == '1' }

	def color_enum
	    ['red','green','yellow','blue']
	end

	scope :published, -> { where(published: true).order('position ASC') }
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  belongs_to :slide
  has_attached_file :picture,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
	  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	  # add a delete_<asset_name> method: 
	  attr_accessor :delete_picture
	  before_validation { self.picture.clear if self.delete_picture == '1' }
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :slide
  has_attached_file :photo,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
	  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
	  # add a delete_<asset_name> method: 
	  attr_accessor :delete_photo
	  before_validation { self.photo.clear if self.delete_photo == '1' }
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :slide
  has_attached_file :picture,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
	  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	  # add a delete_<asset_name> method: 
	  attr_accessor :delete_picture
	  before_validation { self.picture.clear if self.delete_picture == '1' }
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :page
  has_one :video
  has_many :clients, -> { where(published: true).order('position ASC')  }
  has_many :courses, -> { order 'position asc' }
  has_many :partners, -> { order 'position asc' }
  has_many :services, -> { order 'position asc' }
  has_many :people, -> { order 'position asc' }
  has_many :testimonials, -> { where(published: true).order('position ASC') }
  has_attached_file :picture,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
	  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	  # add a delete_<asset_name> method: 
	  attr_accessor :delete_picture
	  before_validation { self.picture.clear if self.delete_picture == '1' }
end

app/models/social.rb
class Social < ActiveRecord::Base
	has_attached_file :picture,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
	  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	  # add a delete_<asset_name> method: 
	  attr_accessor :delete_picture
	  before_validation { self.picture.clear if self.delete_picture == '1' }
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :slide
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :slide
  has_attached_file :m4v
  has_attached_file :mp4
  has_attached_file :ogv
  has_attached_file :webm
  has_attached_file :poster,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
	  validates_attachment_content_type :poster, :content_type => /\Aimage\/.*\Z/
	  # add a delete_<asset_name> method: 
	  attr_accessor :delete_poster
	  before_validation { self.poster.clear if self.delete_poster == '1' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@pages = Page.published
    	@socials = Social.all.order('position ASC')
		render layout: 'main'

	end
	def new
	  	@contact = Contact.new(contact_params)
	  	@result = false
	  	if @contact.save
	   		UserMailer.callback_email(@contact).deliver_now
	   		@result = true
	   	end
	   	 
	end

  def create
   
  end
	private
	    def contact_params
	      params.require(:contact).permit(:name, :email, :phone, :comment, :subject)
	    end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def error404
  	@pages = Page.published
    @socials = Social.all.order('position ASC')
    render status: :not_found, layout: 'main'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	before_action :set_page, only: [:show]

	def index

    @pages = Page.published
    @socials = Social.all.order('position ASC')
    @clients = Client.show
		@partners = Partner.all.order('position ASC')
		render layout: 'main'
  end

  def show
    @contact = Contact.new
    @pages = Page.published
    @socials = Social.all.order('position ASC')
      
		render layout: 'pages'
  end

  def set_page
    @page = Page.friendly.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for :contact, url: contacts_path, :html => {:class => 'top30 contact-form'} do |f| %>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <i class="icon-avatar"></i>
                 <%=f.text_field(:name, class: 'form-control', id: 'name', required: true, placeholder: 'Name ...')%>
            </div>
        </div>
        <div class="col-sm-6">
           <div class="form-group">
                <i class="icon-phone-call"></i>
                    <%=f.telephone_field(:phone, class: 'form-control', id: 'phone', required: true, placeholder: 'Phone ...')%>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <i class="icon-envelope"></i>
                <%=f.email_field(:email, class: 'form-control', id: 'email', required: true, placeholder: 'Email ...')%>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <i class="icon-chat"></i>
                 <%=f.text_field(:subject, class: 'form-control', id: 'subject', placeholder: 'Subject ...')%>
             </div>
         </div>
         <div class="col-sm-12">
            <div class="form-group">
                <%=f.text_area(:comment, class: 'form-control', id: 'comment', placeholder: 'Message ...')%>
            </div>
        </div>

        <div class="col-sm-12">
            <button type="submit"  class="btn btn-rounded btn-border pull-right top20">
                SEND MESSAGE
            </button>
        </div> 
    </div> 
<% end %>

app/views/contacts/_short_form.html.erb
<%= form_for :contact, url: contacts_path, :html => {:class => 'top30 contact-form'} do |f| %>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <i class="icon-avatar"></i>
                 <%=f.text_field(:name, class: 'form-control', id: 'name', required: true, placeholder: 'Name ...')%>
            </div>
        </div>
        <div class="col-sm-6">
           <div class="form-group">
                <i class="icon-phone-call"></i>
                    <%=f.telephone_field(:phone, class: 'form-control', id: 'phone', required: true, placeholder: 'Phone ...')%>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <i class="icon-envelope"></i>
                <%=f.email_field(:email, class: 'form-control', id: 'email', required: true, placeholder: 'Email ...')%>
            </div>
        </div>

        <div class="col-sm-12">
            <button type="submit" class="btn btn-rounded btn-border pull-right top20">
                Contact Us!
            </button>
        </div> 
    </div> 
<% end %>

app/views/contacts/index.html.erb
<section class="main-page">
    <div class="block">
        <div class="text">
           <h1>Thank you!</h1>
           Thank you for your email.  We will be in touch shortly and hope to be able to help you with your requirements.
        </div>
        <a href="/" class="btn btn-rounded btn-red btn-full">HOME PAGE</a>
    </div>
</section>

  <!-- Google Code for Form Submit Conversion Page -->

<script type="text/javascript">



var google_conversion_id = 874069777;

var google_conversion_language = "en";

var google_conversion_format = "3";

var google_conversion_color = "ffffff";

var google_conversion_label = "iQKjCKnorWoQkf7koAM";

var google_remarketing_only = false;


</script>

<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">

</script>

<noscript>

<div style="display:inline;">

<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/874069777/?label=iQKjCKnorWoQkf7koAM&amp;guid=ON&amp;script=0"/>

</div>


</noscript>
<script type="text/javascript">

$(document).ready(function () {
	setTimeout(function(){
		window.location.href = 'http://insightfulhr.com/';
	}, 5000);
});
</script>

app/views/contacts/new.json.erb
<%=@result%>